language: java
jdk: openjdk11
before_script:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
script:
  ./mvnw --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
deploy:
  - provider: script
    script: ./mvnw --batch-mode --settings .maven.xml clean deploy -Prelease
    on:
      branch: master
      tags: true
