language: java
dist: xenial # uses jdk 11 by default
script:
  ./mvnw --batch-mode --settings .maven.xml install
before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh --drop-existing
  on:
    branch: master
    tags: true
