language: java
dist: xenial # uses jdk 11 by default
install:
  - ./mvnw --batch-mode --settings .maven.xml install
before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
deploy:
  provider: script
  script: bash build-and-deploy.sh
